const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('overlay', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  trustProject: () => ipcRenderer.invoke('projects:trust'),
  getRecentMemories: () => ipcRenderer.invoke('memories:recent'),
  addMemory: (memory) => ipcRenderer.invoke('memories:add', memory),
  searchMemories: (query) => ipcRenderer.invoke('memories:search', query),
  getFeelings: () => ipcRenderer.invoke('feelings:get'),
  webSearch: (payload) => ipcRenderer.invoke('web:search', payload),
  getMasterStatus: () => ipcRenderer.invoke('master:status'),
  beginMasterChallenge: (phrase) => ipcRenderer.invoke('master:begin', phrase),
  verifyMasterChallenge: (answer) => ipcRenderer.invoke('master:verify', answer),
  lockMasterAccess: () => ipcRenderer.invoke('master:lock'),
  getSelfUpdateStatus: () => ipcRenderer.invoke('selfupdate:status'),
  unlockSelfUpdate: (payload) => ipcRenderer.invoke('selfupdate:unlock', payload),
  lockSelfUpdate: () => ipcRenderer.invoke('selfupdate:lock'),
  requestEditPermission: () => ipcRenderer.invoke('permissions:edit:request'),
  getEditPermission: () => ipcRenderer.invoke('permissions:edit:get'),
  revokeEditPermission: () => ipcRenderer.invoke('permissions:edit:revoke'),
  requestControlPermission: () => ipcRenderer.invoke('permissions:control:request'),
  getControlPermission: () => ipcRenderer.invoke('permissions:control:get'),
  revokeControlPermission: () => ipcRenderer.invoke('permissions:control:revoke'),
  openFile: () => ipcRenderer.invoke('files:open'),
  saveFile: (payload) => ipcRenderer.invoke('files:save', payload),
  createFile: (payload) => ipcRenderer.invoke('files:create', payload),
  captureScreen: () => ipcRenderer.invoke('capture:screen'),
  runCommand: (payload) => ipcRenderer.invoke('system:run', payload),
  gitStatus: (payload) => ipcRenderer.invoke('git:status', payload),
  gitLog: (payload) => ipcRenderer.invoke('git:log', payload),
  gitDiff: (payload) => ipcRenderer.invoke('git:diff', payload),
  gitCommit: (payload) => ipcRenderer.invoke('git:commit', payload),
  createTask: (payload) => ipcRenderer.invoke('tasks:create', payload),
  listTasks: (limit) => ipcRenderer.invoke('tasks:list', limit),
  getTask: (taskId) => ipcRenderer.invoke('tasks:get', taskId),
  getTaskEvents: (taskId, limit) => ipcRenderer.invoke('tasks:events', taskId, limit),
  approveTaskStep: (payload) => ipcRenderer.invoke('tasks:approve-step', payload),
  cancelTask: (taskId) => ipcRenderer.invoke('tasks:cancel', taskId),
  workflowEdit: (payload) => ipcRenderer.invoke('workflow:edit', payload),
  runWorkflowChecks: (payload) => ipcRenderer.invoke('workflow:verify', payload),
  checkOllama: () => ipcRenderer.invoke('ollama:health'),
  chat: (messages, context) => ipcRenderer.invoke('ollama:chat', { messages, context }),
  onChunk: (handler) => ipcRenderer.on('ollama:chunk', (_evt, chunk) => handler(chunk)),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
});
